apiVersion: v1
kind: Secret
metadata:
  name: baeksungbus-secret
  namespace: baeksungbus
type: Opaque
stringData:
  DB_USER: "test_user"
  DB_PASSWORD: "change-me"
  MYSQL_ROOT_PASSWORD: "change-me"
  MIDDLEWARE_SECRET: "change-me"
  DOCS_ID: "bsbus"
  DOCS_PASSWORD: "change-me"
  EMAIL_USERNAME: "baeksungbus@gmail.com"
  EMAIL_PASSWORD: "change-me"
  EMAIL_SERVER: "smtp.gmail.com"
  EMAIL_PORT: "587"
